const category = {
  gamesPlayed: 'Games Played',
  groundOuts: 'Ground Outs',
  airOuts: 'Fly Outs',
  doubles: 'Doubles',
  triples: 'Triples',
  homeRuns: 'Home Runs',
  strikeOuts: 'Strike Outs',
  baseOnBalls: 'Walks',
  intentionalWalks: 'Intentional Walks',
  hits: 'Hits',
  hitByPitch: 'Hit By Pitch',
  avg: 'Batting Average',
  atBats: 'At Bats',
  obp: 'On Base %',
  slg: 'Slugging %',
  ops: 'On Base + Slugging %',
  groundIntoDoublePlay: 'GIDP',
  groundIntoTriplePlay: 'GITP',
  numberOfPitches: '# of Pitches',
  plateAppearances: 'Plate Appearances',
  totalBases: 'Total Bases',
  rbi: 'Runs Batted In',
  leftOnBase: 'Runners Left On Base',
  sacBunts: 'Sac Bunts',
  sacFlies: 'Sac Flies',
  babip: 'BABIP',
  groundOutsToAirouts: 'GO to FO Ratio',
  catchersInterference: 'Catchers Interference',
  atBatsPerHomeRun: 'At Bats / Home Run',
};

export default category